#!/bin/bash
#
# Name:         chiamerge
# Author:       efnats
# Purpose:
#
# Syntax:	chiamerge.sh  [--option]...  arguments...
#
#		- options are actions to be performed
#		- arguments are disknames
#
# Options:	--chia-init-disk 	(same as: --wipe --format --label --write-sn)
#		--wipe
#	 	--format 		(formats using the default FSTYPE defined in the script)
#		--format-ext4 		(formats as an ext4 filesystem)
#		--format-xfs 		(formats as an xfs filesystem)
#		--label
#		--write-sn
#       --mount-disk
#       --unmount-disk
#		--help
#
# If no option is given, help is shown and the script exits.
#
# Arguments:	one or more disknames (eg: sda sdb-sdd)
#
# At least one argument (diskname) is to be given to the script.
#
# Usage 1: 	chiamerge <diskname>...	
# Example:	chiamerge sda
#			chiamerge sda-sdd
#			chiamerge sda sdd-sdf sdj
#
# Usage 2:	chiamerge <action> <diskname> <disknamerange> ... (in any order)
# Example:	chiamerge --wipe sda sdc-sdg sdh
#			chiamerge --wipe sda sdb --format sdc
##
#########################################################################################################

###################################
#      Configuration       #
###################################

DEBUGLEVEL=1
FSTYPE=ext4
EXT4OPTIONS="-F -m 0 -T largefile4"
XFSOPTIONS="-f -b size=1024"
SERIALNRPREFIX="CHIA"
LOGFILE="./chiamerge.log"

###################################
#        F U N C T I O N S        #
###################################

help()
{
	USAGE="$(basename "$0") [--option]...  argument..."
	echo ${USAGE}
	cat <<END		

		- options are actions to be performed
		- argements are disknames

 Options:	--chia-init-disk (same as: --wipe --format --label --write-sn)
		--wipe
	 	--format
		--format-ext4
		--format-xfs
		--label
		--write-sn
		--help

 If no option is given, help is shown and the script exits.

 Arguments:	one or more disknames (eg: sda sdb-sdd)

 At least one argument (diskname) is to be given to the script.

 Usage 1: 	chiamerge <diskname>...	
 Example:	chiamerge sda
			chiamerge sda-sdd
			chiamerge sda sdd-sdf sdj

 Usage 2:	chiamerge <action> <diskname> <disknamerange> ... (in any order)
 Example:	chiamerge --wipe sda sdc-sdg sdh
			chiamerge --wipe sda sdb --format sdc
END

	echo "> END: ${TIMESTAMP}-------------------------------------------------------" >> ${LOGFILE}

	exit
}

wipe()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}
		
		# If the device is already mounted, don't perform any destructive action on it
#		lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE}'1' is mounted on ${MOUNTPOINT} - ignoring disk."; continue
	
		# Wipe the Disk
		echo -ne wiping...'\t''\t''\t' "${i} "
		
		case ${DEBUGLEVEL} in
			0) wipefs -a ${DEVICE} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) wipefs -a ${DEVICE} >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		sync
	done
}

format()
{
	for i in "$@"
	do
		DEVICE=/dev/${i}

		# If the device is already mounted, don't perform any destructive action on it
		#lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE}'1' is mounted on ${MOUNTPOINT} - ignoring disk."; continue

		# Partition the Disk
		echo -ne creating partition...'\t''\t' "${i} "

		case ${DEBUGLEVEL} in
			0) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		
        # Create filesystem for large files, no reserved space
		echo -n -ne creating $FSTYPE filesystem...'\t' "${i} "

		case ${FSTYPE} in
			ext4) FSOPTIONS=${EXT4OPTIONS};;
			xfs)  FSOPTIONS=${XFSOPTIONS};;
			*)    ;;
		esac

		case ${DEBUGLEVEL} in
			0) mkfs.${FSTYPE} ${FSOPTIONS} ${DEVICE}'1' >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) mkfs.${FSTYPE} ${FSOPTIONS} ${DEVICE}'1' >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		echo ""
	done
}

format-ext4()
{
	for i in "$@"
	do
		DEVICE=/dev/${i}

		# If the device is already mounted, don't perform any destructive action on it
		#lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE}'1' is mounted on ${MOUNTPOINT} - ignoring disk."; continue

		# Partition the Disk
		echo -ne creating partition...'\t''\t' "${i} "

		case ${DEBUGLEVEL} in
			0) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		# Create filesystem for large files, no reserved space
		echo -ne creating EXT4 filesystem...'\t' "${i} "

		case ${DEBUGLEVEL} in
			0) mkfs.ext4 ${EXT4OPTIONS} ${DEVICE}'1' >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) mkfs.ext4 ${EXT4OPTIONS} ${DEVICE}'1' >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		echo ""
	done
}

format-xfs()
{
	for i in "$@"
	do
		DEVICE=/dev/${i}

		# If the device is already mounted, don't perform any destructive action on it
		#lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE}'1' is mounted on ${MOUNTPOINT} - ignoring disk."; continue

		# Partition the Disk
		echo -ne creating partition...'\t''\t' "${i} "

		case ${DEBUGLEVEL} in
			0) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		# Create filesystem for large files, no reserved space and label partition
		echo -ne creating XFS filesystem...'\t' "${i} "

		case ${DEBUGLEVEL} in
			0) mkfs.xfs ${XFSOPTIONS} ${DEVICE}'1' >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) mkfs.xfs ${XFSOPTIONS} ${DEVICE}'1' >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		echo ""
	done
}

label()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}

		# Get serial number of disk
		SERIALNR=$(smartctl -i ${DEVICE} | grep -i "Serial Number" | awk  '{ print $3 }')

		# Label the partition
		echo -ne labelling ${SERIALNRPREFIX}-${SERIALNR}...'\t' "${i} "

		case ${FSTYPE} in
			ext4) LABEL="tune2fs -L";;
			xfs)  LABEL="xfs_admin -L";;
			*)    ;;
		esac

		case ${DEBUGLEVEL} in
			0) $LABEL "${SERIALNRPREFIX}-${SERIALNR}" ${DEVICE}'1' >  /dev/null   2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) $LABEL "${SERIALNRPREFIX}-${SERIALNR}" ${DEVICE}'1' >> ${LOGFILE}  2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac
	done
}

write-sn()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}
		MOUNTPOINT=/media/chiamerge

		# Get serial number of disk
		SERIALNR=$(smartctl -i ${DEVICE} | grep -i "Serial Number" | awk  '{ print $3 }')

		# Write serial number
		echo -ne creating file $SERIALNR in...'\t' "${i} "

		mkdir -p ${MOUNTPOINT}/${i}1
		mount ${DEVICE}1 ${MOUNTPOINT}/${i}1

		case ${DEBUGLEVEL} in
			0) mkdir -p ${MOUNTPOINT}/${i}1/serial && touch ${MOUNTPOINT}/${i}1/serial/${SERIALNR} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) mkdir -p ${MOUNTPOINT}/${i}1/serial && touch ${MOUNTPOINT}/${i}1/serial/${SERIALNR} >> ${LOGFILE} 2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

		umount ${MOUNTPOINT}/${i}1
		rm -r ${MOUNTPOINT}/${i}1
	done
}

## howto detect unmounted disks
## lsblk --noheadings --raw -o NAME,MOUNTPOINT | awk '$1~/[[:digit:]]/ && $2 == ""' 

mount-disk()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}
		MOUNTPOINT=/media/${SERIALNRPREFIX}

		# Mount drive
		echo -ne Mounting disk...'\t' "${i} "

#		mkdir -p ${MOUNTPOINT}/${i}1 &&	mount ${DEVICE}1 ${MOUNTPOINT}/${i}1

		case ${DEBUGLEVEL} in
			0) mkdir -p ${MOUNTPOINT}/${i}1 &&	mount ${DEVICE}1 ${MOUNTPOINT}/${i}1 >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) mkdir -p ${MOUNTPOINT}/${i}1 &&	mount ${DEVICE}1 ${MOUNTPOINT}/${i}1 >> ${LOGFILE} 2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

	done
}


umount-disk()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}
		MOUNTPOINT=/media/${SERIALNRPREFIX}

		# Unmount drive
		echo -ne Unmounting disk...'\t' "${i} "

		case ${DEBUGLEVEL} in
			0) umount ${MOUNTPOINT}/${i}1 && rm -r ${MOUNTPOINT}/${i}1 >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;

			1) umount ${MOUNTPOINT}/${i}1 && rm -r ${MOUNTPOINT}/${i}1 >> ${LOGFILE} 2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}ERROR${NOCOLOR}";;
		esac

	done
}

warningmesg()
{
	ACTIONS="$1"
	DEVICEOPTIONSLIST="$2"

	echo "Welcome to chiamerge V(${VERSION})"
	echo ""
	echo "You have chosen to perform the following actions: ${BOLD}${ACTIONS}${NORM}"
	echo "on disks: ${BOLD}${DEVICEOPTIONSLIST}${NORM}"

	grep -wqe "format\|wipe" <<< ${ACTIONS} && echo -e "\n${RED}WARNING!!\n\nThis is going to IRREVERSIBLY DESTROY all data on ${NOCOLOR}${BOLD}${DEVICEOPTIONSLIST}${NORM}\n"

	read -p "Do you really want to do that? (y/n): " ANS
	echo  ""

	if [[ ${ANS} == [nN] ]] 
	then
		case ${DEBUGLEVEL} in
			0) exit 1;;

			1) echo "> END: ${TIMESTAMP} ---------------------------------------------------------" >> ${LOGFILE}
			   exit 1;;
		esac
	fi
}


###################################
#      M A I N    L O G I C       #
###################################

# Variables
VERSION="0.84"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
#SERIALNR=$(hdparm -I ${DEVICE} | awk '/Serial Number/ { print $3 }')
#SERIALNR=$(smartctl -i ${DEVICE} | grep -i "Serial Number" | awk  '{ print $3 }')

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`

WORDOPTIONSLIST=""
DEVICEOPTIONSLIST=""

# Send output and error to log file
if [[ ${DEBUGLEVEL} -eq 1 ]]
then
	exec > >(tee -a ${LOGFILE})
	exec 2>&1
fi

echo ""											    >> ${LOGFILE}
echo "------------------------------------------------------------------------------------" >> ${LOGFILE}
echo "BEGIN: ${BOLD}${TIMESTAMP}${NORM}"						    >> ${LOGFILE}
echo "------------------------------------------------------------------------------------" >> ${LOGFILE}

# Process all the arguments given to the script
for i in "$@"
do
	# Get the first two characters of the option
	FIRSTTWOCHAR=$(echo $i | cut -c1-2)

	# It is a word option if the first two characters are hyphens
	if [[ ${FIRSTTWOCHAR} == "--" ]]
	then
		REMAININGWORDOPTION=$(echo "${i:2}")
		WORDOPTIONSLIST="${WORDOPTIONSLIST} ${REMAININGWORDOPTION}"

	# If not, then look for hyphen in the option. If it exists, it is a device range option
	elif [[ $i =~ "-" ]]
	then
		# Extract first and last device names
		FIRSTDEVICE=$(echo $i | cut -d'-' -f1)
		LASTDEVICE=$(echo $i | cut -d'-' -f2)

		# Calculate their lengths
		LENFIRSTDEVICE=$(echo ${#FIRSTDEVICE})
		LENLASTDEVICE=$(echo ${#LASTDEVICE})

		# Find the device prefix from first device
		DEVPREFIX=$(echo ${FIRSTDEVICE%?})

		# Find the difference in length between both devices
		LENDIFF=$((LENLASTDEVICE - LENFIRSTDEVICE))

		#echo FIRSTDEVICE is $FIRSTDEVICE
		#echo LASTDEVICE is $LASTDEVICE
		#echo DEVPREFIX is $DEVPREFIX
		#echo LENDIFF is $LENDIFF

		case ${LENDIFF} in
			0) FIRSTLTR3=$(echo "${FIRSTDEVICE: -1}")
			   LASTLTR3=$(echo "${LASTDEVICE: -1}")
			   #echo "In 0. FIRSTLTR is $FIRSTLTR  LASTLTR is $LASTLTR."
			   EXPANDEDLIST=$(eval echo ${DEVPREFIX}{$FIRSTLTR3..$LASTLTR3});;

			1) FIRSTLTR3=$(echo "${FIRSTDEVICE: -1}")
			   LASTLTR4=$(echo "${LASTDEVICE: -1}")
			   LASTLTR3=$(echo "${LASTDEVICE: -2}" | cut -c1)
			   NUMLASTLTR3=$(printf "%d\n" \'$LASTLTR3)
			   let NUMLASTLTR3=$NUMLASTLTR3-1
			   LASTLTR3PREV=$(printf "\x$(printf %x $NUMLASTLTR3)")

			   #echo "In 1. FIRSTLTR3 is $FIRSTLTR3  LASTLTR4 is $LASTLTR4 LASTLTR3 is $LASTLTR3."
			   LIST1=$(eval echo ${DEVPREFIX}{$FIRSTLTR3..z})
			   LIST2=$(eval echo ${DEVPREFIX}{a..$LASTLTR3PREV}{a..z})
			   LIST3=$(eval echo ${DEVPREFIX}$LASTLTR3$LASTLTR4)
			   EXPANDEDLIST=$(echo $LIST1 $LIST2 $LIST3);;
	        esac

		DEVICEOPTIONSLIST="${DEVICEOPTIONSLIST} ${EXPANDEDLIST}"

	# Else, consider it as a single device option
	else
		DEVICEOPTIONSLIST="${DEVICEOPTIONSLIST} ${i}"
	fi
done

DEVICEOPTIONSLIST=$(echo ${DEVICEOPTIONSLIST} | xargs)
WORDOPTIONSLIST=$(echo ${WORDOPTIONSLIST} | xargs)

#echo "DEVICEOPTIONSLIST is ${DEVICEOPTIONSLIST}"
#echo "WORDOPTIONSLIST   is ${WORDOPTIONSLIST}"

# If option given is --help or one of the options given is --help
if grep -wqe "help" <<< ${WORDOPTIONSLIST}
then
		ACTIONS="help"
		echo "Welcome to chiamerge V(${VERSION})"
		echo ""
		help

# If no disk(s) given
elif [[ -z ${DEVICEOPTIONSLIST} ]]
then
	# and no word options given, default to --help optiion.
	if [[ -z ${WORDOPTIONSLIST} ]] || [[ ${WORDOPTIONSLIST} == "help" ]]
	then
		ACTIONS="help"
		echo "Welcome to chiamerge V(${VERSION})"
		echo ""
	fi

# If disk(s) given and action given is: chia-init-disk
elif [[ "${WORDOPTIONSLIST}" == "chia-init-disk" ]]
then
	ACTIONS="wipe format label write-sn"
	warningmesg "${ACTIONS}" "${DEVICEOPTIONSLIST}"

# Else, run the specified action on all the devices given as arguments
else
	ACTIONS="${WORDOPTIONSLIST}"
	warningmesg "${ACTIONS}" "${DEVICEOPTIONSLIST}"
fi

#echo "ACTIONS is ${ACTIONS}"

for ACTION in ${ACTIONS}
do
	case ${ACTION} in
		help)		help;;

		wipe) 		echo -e		"${BOLD}\nWipe${NORM}"
				wipe    	${DEVICEOPTIONSLIST};;

		format) 	echo -e		"${BOLD}\nFormat${NORM}"
				format  	${DEVICEOPTIONSLIST};;

		format-ext4) 	echo -e		"${BOLD}\nFormat${NORM}"
				format-ext4  	${DEVICEOPTIONSLIST};;

		format-xfs) 	echo -e		"${BOLD}\nFormat${NORM}"
				format-xfs  	${DEVICEOPTIONSLIST};;

		label)		echo -e		"${BOLD}\nLabel${NORM}"
				label   	${DEVICEOPTIONSLIST};;

		write-sn)	echo -e		"${BOLD}\nWrite serialfile${NORM}"
				write-sn   	${DEVICEOPTIONSLIST};;

		mount-disk)	echo -e		"${BOLD}\nMount disk${NORM}"
				mount-disk   	${DEVICEOPTIONSLIST};;

		umount-disk)	echo -e		"${BOLD}\nUnmount disk${NORM}"
		    	umount-disk   	${DEVICEOPTIONSLIST};;


		*)		echo    	"Invalid action specified";;
	esac
done

#echo "FSTYPE is ${FSTYPE}"
#echo "FSOPTIONS is ${FSOPTIONS}"

TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

echo -e "\n\n> END: ${TIMESTAMP} ----------------------------------------------------------------" >> ${LOGFILE}
#
#END#
#########################################################################################################
