#!/bin/bash
#
# Name:         chiaman
# Author:       efnats
# Purpose:
#
# Syntax:	chiaman.sh  [--option]...  arguments...
#
#		- options are actions to be performed
#		- arguments are disknames
#
# Options:	--chia-init-disk (same as: --wipe --format --label --write-sn)
#		--wipe
#	 	--format
#		--label
#		--write-sn
#		--help
#
# If no option is given, help is shown and the script exits.
#
# Arguments:	one or more disknames (eg: sda sdb-sdd)
#
# At least one argument (diskname) is to be given to the script.
#
# Usage 1: 	chiaman <diskname>...	
# Example:	chiaman sda
#		chiaman sda-sdd
#		chiaman sda sdd-sdf sdj
#
# Usage 2:	chiaman <action> <diskname> <disknamerange> ... (in any order)
# Example:	chiaman --wipe sda sdc-sdg sdh
#		chiaman --wipe sda sdb --format sdc
#
# To Do:
# -----
#
# 1. help text the the options overview; print it when script is called with -h, --help
#    or without any arguments.
#
# 2. Display Spinner while waiting for each task to finish (especially useful for mkfs command)
#    https://unix.stackexchange.com/questions/225179/
#
# 3. Filters for hhds. Replace selection of hdds with an array gathered from lsblk
#
# 4. Ignore the disk if it has a mount point
#
# 5. (Postponed) Add support for extended drive ranges: sda-sdzz
#
#########################################################################################################

###################################
#        F U N C T I O N S        #
###################################

help()
{
	USAGE="$(basename "$0") [--option]...  argument..."
	echo ${USAGE}
	cat <<END		

		- options are actions to be performed
		- argements are disknames

 Options:	--chia-init-disk (same as: --wipe --format --label --write-sn)
		--wipe
	 	--format
		--label
		--write-sn
		--help

 If no option is given, help is shown and the script exits.

 Arguments:	one or more disknames (eg: sda sdb-sdd)

 At least one argument (diskname) is to be given to the script.

 Usage 1: 	chiaman <diskname>...	
 Example:	chiaman sda
		chiaman sda-sdd
		chiaman sda sdd-sdf sdj

 Usage 2:	chiaman <action> <diskname> <disknamerange> ... (in any order)
 Example:	chiaman --wipe sda sdc-sdg sdh
		chiaman --wipe sda sdb --format sdc
END

	echo "> END: ${TIMESTAMP}-------------------------------------------------------" >> ${LOGFILE}

	exit
}

wipe()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}
		
		# If the device is already mounted, don't perform any destructive action on it
#		lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE}'1' is mounted on ${MOUNTPOINT} - ignoring disk."; continue
	
		# Wipe the Disk
		echo -n "${i}..."
		
		case ${DEBUGLEVEL} in
			0) wipefs -a ${DEVICE} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

			1) wipefs -a ${DEVICE} >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
		esac

		sync
	done
}

format()
{
	for i in "$@"
	do
		DEVICE=/dev/${i}

		# If the device is already mounted, don't perform any destructive action on it
#		lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE}'1' is mounted on ${MOUNTPOINT} - ignoring disk."; continue

		# Partition the Disk
		echo -n "${i}..."

		case ${DEBUGLEVEL} in
			0) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

			1) echo -e "g\nn\n1\n\n\nw" | fdisk ${DEVICE} >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
		esac

		# Get serial number of Disk
		SERIALNR=$(hdparm -I ${DEVICE} | awk '/Serial Number/ { print $3 }')

                # Create filesystem ext4 for large files, no reserved space and label partition
		echo -n "mkfs on ${i}..."

		case ${DEBUGLEVEL} in
			0) mkfs.ext4 ${MKFSOPTIONS} "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE}'1' >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

			1) mkfs.ext4 ${MKFSOPTIONS} "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE}'1' >> ${LOGFILE} 2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
		esac

		echo ""
	done
}

label()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}

		# Get serial number of disk
		SERIALNR=$(hdparm -I ${DEVICE} | awk '/Serial Number/ { print $3 }')

		# Label the partition
		echo -n "${i}..."

		case ${DEBUGLEVEL} in
			0) tune2fs -L "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE}'1' >  /dev/null   2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

			1) tune2fs -L "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE}'1' >> ${LOGFILE}  2>&1 
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
		esac
	done
}

write-sn()
{
	for i in "$@"
	do
        	DEVICE=/dev/${i}
		MOUNTPOINT=/mnt/chiaman

		# Get serial number of disk
		SERIALNR=$(hdparm -I ${DEVICE} | awk '/Serial Number/ { print $3 }')

		# Write serian number
		echo -n "${i}..."

		mkdir -p ${MOUNTPOINT}/${i}1
		mount ${DEVICE}1 ${MOUNTPOINT}/${i}1

		case ${DEBUGLEVEL} in
			0) mkdir -p ${MOUNTPOINT}/${i}1/serial && touch ${MOUNTPOINT}/${i}1/serial/${SERIALNR} >  /dev/null  2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

			1) mkdir -p ${MOUNTPOINT}/${i}1/serial && touch ${MOUNTPOINT}/${i}1/serial/${SERIALNR} >> ${LOGFILE} 2>&1
			   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
		esac

		umount ${MOUNTPOINT}/${i}1
		rm -r ${MOUNTPOINT}/${i}1
	done
}

warningmesg()
{
	ACTIONS="$1"
	DEVICEOPTIONSLIST="$2"

	echo "Welcome to chiaman V(${VERSION})"
	echo ""
	echo "You have chosen to perform the following actions: ${BOLD}${ACTIONS}${NORM}"
	echo "on disks: ${BOLD}${DEVICEOPTIONSLIST}${NORM}"

	grep -wqe "format\|wipe" <<< ${ACTIONS} && echo -e "\n${RED}WARNING!!\n\nThis is going to IRREVERSIBLY DESTROY all data on ${NOCOLOR}${BOLD}${DEVICEOPTIONSLIST}${NORM}\n"

	read -p "Do you really want to do that? (y/n): " ANS
	echo  ""

	if [[ ${ANS} == [nN] ]] 
	then
		case ${DEBUGLEVEL} in
			0) exit 1;;

			1) echo "> END: ${TIMESTAMP} ---------------------------------------------------------" >> ${LOGFILE}
			   exit 1;;
		esac
	fi
}


###################################
#      M A I N    L O G I C       #
###################################

# Variables
VERSION="0.83"
LOGFILE="./chiaman.log"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")
DEBUGLEVEL=1
SERIALNRPREFIX="CHIA-"
MKFSOPTIONS=" -F -m 0 -T largefile4 -L "

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"
NORM=`tput sgr0`
BOLD=`tput bold`
REV=`tput smso`

WORDOPTIONSLIST=""
DEVICEOPTIONSLIST=""

# Send output and error to log file
if [[ ${DEBUGLEVEL} -eq 1 ]]
then
	exec > >(tee -a ${LOGFILE})
	exec 2>&1
fi

echo ""											    >> ${LOGFILE}
echo "------------------------------------------------------------------------------------" >> ${LOGFILE}
echo "BEGIN: ${BOLD}${TIMESTAMP}${NORM}"						    >> ${LOGFILE}
echo "------------------------------------------------------------------------------------" >> ${LOGFILE}

# Process all the arguments given to the script
for i in "$@"
do
	# Get the first two characters of the option
	FIRSTTWOCHAR=$(echo $i | cut -c1-2)

	# It is a word option if the first two characters are hyphens
	if [[ ${FIRSTTWOCHAR} == "--" ]]
	then
		REMAININGWORDOPTION=$(echo "${i:2}")
		WORDOPTIONSLIST="${WORDOPTIONSLIST} ${REMAININGWORDOPTION}"

	# If not, then look for hyphen in the option. If it exists, it is a device range option
	elif [[ $i =~ "-" ]]
	then
		# Extract first and last device names
		FIRSTDEVICE=$(echo $i | cut -d'-' -f1)
		LASTDEVICE=$(echo $i | cut -d'-' -f2)

		# Calculate their lengths
		LENFIRSTDEVICE=$(echo ${#FIRSTDEVICE})
		LENLASTDEVICE=$(echo ${#LASTDEVICE})

		# Find the device prefix from first device
		DEVPREFIX=$(echo ${FIRSTDEVICE%?})

		# Find the difference in length between both devices
		LENDIFF=$((LENLASTDEVICE - LENFIRSTDEVICE))

		#echo FIRSTDEVICE is $FIRSTDEVICE
		#echo LASTDEVICE is $LASTDEVICE
		#echo DEVPREFIX is $DEVPREFIX
		#echo LENDIFF is $LENDIFF

		case ${LENDIFF} in
			0) FIRSTLTR3=$(echo "${FIRSTDEVICE: -1}")
			   LASTLTR3=$(echo "${LASTDEVICE: -1}")
			   #echo "In 0. FIRSTLTR is $FIRSTLTR  LASTLTR is $LASTLTR."
			   EXPANDEDLIST=$(eval echo ${DEVPREFIX}{$FIRSTLTR3..$LASTLTR3});;

			1) FIRSTLTR3=$(echo "${FIRSTDEVICE: -1}")
			   LASTLTR4=$(echo "${LASTDEVICE: -1}")
			   LASTLTR3=$(echo "${LASTDEVICE: -2}" | cut -c1)
			   NUMLASTLTR3=$(printf "%d\n" \'$LASTLTR3)
			   let NUMLASTLTR3=$NUMLASTLTR3-1
			   LASTLTR3PREV=$(printf "\x$(printf %x $NUMLASTLTR3)")

			   #echo "In 1. FIRSTLTR3 is $FIRSTLTR3  LASTLTR4 is $LASTLTR4 LASTLTR3 is $LASTLTR3."
			   LIST1=$(eval echo ${DEVPREFIX}{$FIRSTLTR3..z})
			   LIST2=$(eval echo ${DEVPREFIX}{a..$LASTLTR3PREV}{a..z})
			   LIST3=$(eval echo ${DEVPREFIX}$LASTLTR3$LASTLTR4)
			   EXPANDEDLIST=$(echo $LIST1 $LIST2 $LIST3);;
	        esac

		DEVICEOPTIONSLIST="${DEVICEOPTIONSLIST} ${EXPANDEDLIST}"

	# Else, consider it as a single device option
	else
		DEVICEOPTIONSLIST="${DEVICEOPTIONSLIST} ${i}"
	fi
done

DEVICEOPTIONSLIST=$(echo ${DEVICEOPTIONSLIST} | xargs)
WORDOPTIONSLIST=$(echo ${WORDOPTIONSLIST} | xargs)

#echo "DEVICEOPTIONSLIST is ${DEVICEOPTIONSLIST}"
#echo "WORDOPTIONSLIST   is ${WORDOPTIONSLIST}"

# If no disk(s) given
if [[ -z ${DEVICEOPTIONSLIST} ]]
then
	# and no word options given, default to --help optiion.
	if [[ -z ${WORDOPTIONSLIST} ]] || [[ ${WORDOPTIONSLIST} == "help" ]]
	then
		ACTIONS="help"
		echo "Welcome to chiaman V(${VERSION})"
		echo ""
		help
	fi
# If disk(s) given and action given is: chia-init-disk
elif [[ "${WORDOPTIONSLIST}" == "chia-init-disk" ]]
then
	ACTIONS="wipe format label write-sn"
	warningmesg "${ACTIONS}" "${DEVICEOPTIONSLIST}"

# If disk(s) given and action given is: help
elif [[ ${WORDOPTIONSLIST} == "help" ]]
then
		ACTIONS="help"
		echo "Welcome to chiaman V(${VERSION})"
		echo ""
		help

# Else, run the specified action on all the devices given as arguments
else
	ACTIONS="${WORDOPTIONSLIST}"
	warningmesg "${ACTIONS}" "${DEVICEOPTIONSLIST}"
fi

#echo "ACTIONS is ${ACTIONS}"

for ACTION in ${ACTIONS}
do
	case ${ACTION} in
		help)		help;;

		wipe) 		echo -e		"${BOLD}\nWiping${NORM}"
				wipe    	${DEVICEOPTIONSLIST};;

		format) 	echo -e		"${BOLD}\nFormatting${NORM}"
				format  	${DEVICEOPTIONSLIST};;

		label)		echo -e		"${BOLD}\nLabelling${NORM}"
				label   	${DEVICEOPTIONSLIST};;

		write-sn)	echo -e		"${BOLD}\nWriting empty serialfile${NORM}"
				write-sn   	${DEVICEOPTIONSLIST};;

		*)		echo    	"Invalid action specified";;
	esac
done

TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")

echo -e "\n\n> END: ${TIMESTAMP} ----------------------------------------------------------------" >> ${LOGFILE}
#
#END#
#########################################################################################################
